### PR TITLE
Add SXS Logo

### PR DESCRIPTION
**Pull request by nilsdeppe**
Add the SXS logo PNG so people can use it in talks, etc.

### CODE REVIEW

**Comment by duetosymmetry** [comment]
I have the following zip: [SXS Logo Photoshop Vector and Hi Res Files.zip](https://github.com/sxs-collaboration/WelcomeToSXS/files/8337616/SXS.Logo.Photoshop.Vector.and.Hi.Res.Files.zip) that I think I got from @moble containing other versions of the logo. Include these as well?

**Comment by nilsdeppe** [comment]
I agree! Updated the PR with all the files in the zip. I just unzipped it so people can easily download individual images from the repo

**Review by duetosymmetry — APPROVED** [review]
LGTM!

**Comment by moble** [comment]
Oh, I had been looking for these files.  Thanks, Leo! :)

**Pull request merged**
